name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

# Needed for Pages deployment
permissions:
  contents: read
  pages: write
  id-token: write    

# Prevent overlapping Pages deployments
concurrency:
  group: "pages"
  cancel-in-progress: true  

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    environment: prod
    env: 
      HEROKU_USERNAME: ${{ secrets.HEROKU_USERNAME }}
      HEROKU_PWD: ${{ secrets.HEROKU_PWD }}
      HEROKU_OTP_URI: ${{ secrets.HEROKU_OTP_URI }}

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npx playwright test

    - name: Upload Playwright HTML report (artifact)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
        
    - name: Upload raw test artifacts (videos/screenshots/traces)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-test-results
        path: test-results/
        retention-days: 30

    # ---- Publish HTML report to GitHub Pages (viewable online) ----
    - name: Upload Pages artifact
      if: always()
      uses: actions/upload-pages-artifact@v3
      with:
        path: playwright-report/

    - name: Deploy to GitHub Pages
      if: always()
      id: deployment
      uses: actions/deploy-pages@v4
      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}

    - name: Show deployed URL
      if: always()
      run: echo "Playwright report: ${{ steps.deployment.outputs.page_url }}"